require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PhoneCodesController do

  # This should return the minimal set of attributes required to create a valid
  # PhoneCode. As you add validations to PhoneCode, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all phone_codes as @phone_codes" do
      phone_code = PhoneCode.create! valid_attributes
      get :index
      assigns(:phone_codes).should eq([phone_code])
    end
  end

  describe "GET show" do
    it "assigns the requested phone_code as @phone_code" do
      phone_code = PhoneCode.create! valid_attributes
      get :show, :id => phone_code.id.to_s
      assigns(:phone_code).should eq(phone_code)
    end
  end

  describe "GET new" do
    it "assigns a new phone_code as @phone_code" do
      get :new
      assigns(:phone_code).should be_a_new(PhoneCode)
    end
  end

  describe "GET edit" do
    it "assigns the requested phone_code as @phone_code" do
      phone_code = PhoneCode.create! valid_attributes
      get :edit, :id => phone_code.id.to_s
      assigns(:phone_code).should eq(phone_code)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PhoneCode" do
        expect {
          post :create, :phone_code => valid_attributes
        }.to change(PhoneCode, :count).by(1)
      end

      it "assigns a newly created phone_code as @phone_code" do
        post :create, :phone_code => valid_attributes
        assigns(:phone_code).should be_a(PhoneCode)
        assigns(:phone_code).should be_persisted
      end

      it "redirects to the created phone_code" do
        post :create, :phone_code => valid_attributes
        response.should redirect_to(PhoneCode.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved phone_code as @phone_code" do
        # Trigger the behavior that occurs when invalid params are submitted
        PhoneCode.any_instance.stub(:save).and_return(false)
        post :create, :phone_code => {}
        assigns(:phone_code).should be_a_new(PhoneCode)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PhoneCode.any_instance.stub(:save).and_return(false)
        post :create, :phone_code => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested phone_code" do
        phone_code = PhoneCode.create! valid_attributes
        # Assuming there are no other phone_codes in the database, this
        # specifies that the PhoneCode created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PhoneCode.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => phone_code.id, :phone_code => {'these' => 'params'}
      end

      it "assigns the requested phone_code as @phone_code" do
        phone_code = PhoneCode.create! valid_attributes
        put :update, :id => phone_code.id, :phone_code => valid_attributes
        assigns(:phone_code).should eq(phone_code)
      end

      it "redirects to the phone_code" do
        phone_code = PhoneCode.create! valid_attributes
        put :update, :id => phone_code.id, :phone_code => valid_attributes
        response.should redirect_to(phone_code)
      end
    end

    describe "with invalid params" do
      it "assigns the phone_code as @phone_code" do
        phone_code = PhoneCode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PhoneCode.any_instance.stub(:save).and_return(false)
        put :update, :id => phone_code.id.to_s, :phone_code => {}
        assigns(:phone_code).should eq(phone_code)
      end

      it "re-renders the 'edit' template" do
        phone_code = PhoneCode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PhoneCode.any_instance.stub(:save).and_return(false)
        put :update, :id => phone_code.id.to_s, :phone_code => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested phone_code" do
      phone_code = PhoneCode.create! valid_attributes
      expect {
        delete :destroy, :id => phone_code.id.to_s
      }.to change(PhoneCode, :count).by(-1)
    end

    it "redirects to the phone_codes list" do
      phone_code = PhoneCode.create! valid_attributes
      delete :destroy, :id => phone_code.id.to_s
      response.should redirect_to(phone_codes_url)
    end
  end

end
